Digitalhealthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#static files and media files configuration
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('Patients/', include('patients.urls')),
    path('Doctors/', include('doctors.urls')),
    path('Appointments/', include('appointments.urls')),
    path('Rating/', include('rating.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctors/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.dashboard, name="dashboard"),
    path('DoctorProfile/', views.DoctorProfile, name="DoctorProfile"),
    path('DoctorSignUp/', views.registerDoctor, name="DoctorSignUp"),
    path('DoctorLogin/', views.DoctorLogin, name="DoctorLogin"),
    path('DoctorLogout/', views.DoctorLogout, name="DoctorLogout"),
    path('BrowseDoctors/', views.BrowseDoctors, name="BrowseDoctors"),
    path('DoctorDetail/<int:pk>', views.DoctorDetail, name="doctor_detail"),


    path('Posts/', views.PostList, name='post_list'),
    path('Posts/MyPosts', views.MyPosts, name='my_posts'),
    path('Posts/PostDetail/<int:post_id>/', views.PostDetail, name='post_detail'),
    path('Posts/CreatePost/', views.CreatePost, name='create_post'),
    path('Posts/EditPost/<int:post_id>/', views.EditPost, name='edit_post'),
    path('Posts/DeletePost/<int:post_id>/', views.DeletePost, name='delete_post'),
    path('activate/<uidb64>/<token>/',views.activateAccount , name='activate'),

]

rating/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('rate_doctor/<int:doctor_id>/', views.RateDoctor, name = 'rate_doctor'),        
]

doctors/models.py
from django.db import models
from django.contrib.auth.models import User



class Doctor(models.Model):
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)

    # verification status
    VERIFICATION_STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('declined', 'Declined'),
    )
    verification_message = models.TextField(max_length=1000, blank=True, null=True, default="")
    verification_status = models.CharField(max_length=20, choices=VERIFICATION_STATUS_CHOICES, blank=True, null=True)

    # verification details
    national_id_or_passport_image = models.ImageField(upload_to='doctors/verification', blank=True, null=True)
    phone_number = models.CharField(max_length=14, default=True, blank=True, null=True)
    photo = models.ImageField(upload_to='doctors/account', null=True, blank=True)
    medical_licence = models.ImageField(upload_to='doctors/verification', null=True, blank=True)
    passport_or_id_number = models.CharField(max_length=20, blank=True, null=True)
    date_issued = models.DateField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)

    # specialization
    specialization = models.CharField(max_length=1000, blank=True, null=True, default="")


    city = models.CharField(max_length=100,  blank=True, null=True)

    REGION_CHOICES = (
        ("Afar", "Afar"),
        ("Amhara", "Amhara"),
        ("Benishangul-Gumuz", "Benishangul-Gumuz"),
        ("Gambela", "Gambela"),
        ("Harari", "Harari"),
        ("Oromia", "Oromia"),
        ("Somali", "Somali"),
        ("Southern Nations, Nationalities, and Peoples'", "Southern Nations, Nationalities, and Peoples'"),
        ("Tigray", "Tigray"),
        ("Sidama", "Sidama"),
        ("Nuer", "Nuer"),
        ("Wolayita", "Wolayita"),
    )
    region = models.CharField(max_length=100, choices=REGION_CHOICES, blank=True, null=True)

    country = models.CharField(max_length=100, blank=True, null=True)

    # Years of experience
    YEARS_OF_EXPERIENCE_CHOICES = (
        ("less than 1", "Less than 1 year"),
        ("1-3", "1-3 years"),
        ("3-5", "3-5 years"),
        ("more than 5", "More than 5 years"),
    )
    years_of_experience = models.CharField(max_length=20, choices=YEARS_OF_EXPERIENCE_CHOICES, blank=True, null=True)

    # Languages
    languages = models.CharField(max_length=200, blank=True, null=True)
    

    # ratings
    rating = models.FloatField(default=0.0, null=True, blank=True)
    rating_counter = models.IntegerField(default=0, null=True, blank=True)

   
    def __str__(self):
        return f"Dr. {self.first_name} {self.last_name}"



class Post(models.Model):
    author = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    image_main = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    image1 = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    image2 = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    image3 = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    thumbs_up = models.PositiveIntegerField(default=0)
    liked_by = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def has_liked(self, user):
        return user in self.liked_by.all()  
    
    def __str__(self):
        return self.title

doctors/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Doctor, Post
from .forms import DoctorProfileForm, UserLoginForm, UserForm, ThumbsUpForm, PostForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
#login and logout

from django.contrib.auth import authenticate, login, logout
from django.contrib import auth
from django.contrib.auth.decorators import login_required
#login and logout

#Email verification and account activation
from django.contrib import messages
from .utils import  send_verification_email
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
#Email verification and account activation

#Doctor Rating
from rating.models import Rating

def DoctorDetail(request,pk):
    doctor = Doctor.objects.get(id=pk)
    reviews = Rating.objects.filter(rated_doctor = doctor)
    context = {
        'doctor' : doctor,
        'reviews': reviews,  
    }
    
    return render(request, 'doctors/doctor_detail.html', context)


@login_required(login_url='login')
def DoctorProfile(request):
    doctor = get_object_or_404(Doctor, user=request.user)

    if request.method == 'POST':
        form = DoctorProfileForm(request.POST, request.FILES, instance=doctor)
        if form.is_valid():
            doc = form.save(commit=False)
            doc.date_of_birth = form.cleaned_data['date_of_birth']
            doc.date_issued = form.cleaned_data['date_issued']
            doc.expiry_date = form.cleaned_data['expiry_date']
            doc.save()
            messages.success(request, 'Your profile has been updated successfully.')
            return redirect('DoctorProfile')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
    else:
        form = DoctorProfileForm(instance=doctor)
    return render(request, 'doctors/doctor_profile.html', {'form': form, 'doc': doctor})


def registerDoctor(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        # doc_form = DoctorsProfileForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            # doc = doc_form.save(commit=False)
            # doc.user = user
            # doc.first_name = user_form.cleaned_data['first_name']
            # doc.last_name = user_form.cleaned_data['last_name']
            # doc.save()

            # doc_form = DoctorProfile(request.POST, isinstance=user.doc)

            username = user_form.cleaned_data['username']
            email = user_form.cleaned_data['email']
            password = user_form.cleaned_data['password1']
            user=authenticate(username=username, password=password)
            
             #Send email
            mail_subject = 'Please activate your account'
            email_template = 'doctors/account_verification_email.html'
            send_verification_email(request, user, mail_subject, email_template)

            
            messages.success(request,"Doctor Registred Successfully!")
            login(request,user)            
            return redirect('DoctorProfile')


        else:
            print(user_form.errors)
            for field, errors in user_form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
            context = {'form': user_form} 
    else:
        user_form = UserForm()

    context = {
       
        'user_form':user_form
    }
    return render(request, 'doctors/doctors_registration_page.html', context)


def activateAccount(request, uidb64, token):
    print("*************-------Account Activation-------**************")
   
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)

    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        print("Account Successfully Activated!")
        return redirect('home')
    else:
        print("Invalid Activation Link!")
        return redirect('home')

def DoctorLogin(request):
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password1']

    

    user = authenticate(username=username, password=password)
    if user is not None:
      auth.login(request, user)
      return redirect('DoctorProfile')  
    else:
      # Login failed
      messages.error(request, 'Invalid username or password!')
      return redirect('DoctorLogin')
  
  return render(request, 'doctors/doctors_login.html')
                


from django.db.models import Q


def BrowseDoctors(request):

    if(request.user.is_authenticated):
        if(Doctor.objects.filter(user=request.user).exists()):
            template = 'doctors/search_and_book_doctors.html'
            print("Doctor")
        else:    
            print("Patient")
            template = 'patients/search_and_book_doctors.html'
    else:
        template = 'doctors/browse_doctors.html'


    query = request.GET.get('query', '')
    city = request.GET.get('city', '')
    region = request.GET.get('region', '')
    country = request.GET.get('country', '')
    years_of_experience = request.GET.get('years_of_experience', '')
    languages = request.GET.get('languages', '')
    doctor_type = request.GET.get('doctor_type', '')
    rating = request.GET.get('rating', '')

    doctors = Doctor.objects.filter(verification_status='approved')

    # Filter by city
    if city:
        doctors = doctors.filter(city__iexact=city)

    # Filter by region
    if region:
        doctors = doctors.filter(region__iexact=region)


    # Filter by years of experience
    if years_of_experience:
        doctors = doctors.filter(years_of_experience__gte=years_of_experience)

    # Filter by languages
    if languages:
        doctors = doctors.filter(languages__icontains=languages)

    # Filter by doctor type
    if doctor_type:
        doctors = doctors.filter(doctor_type__iexact=doctor_type)

    # Filter by rating
    if rating:
        doctors = doctors.filter(rating__gte=rating)

    # Search by query
    if query:
        doctors = doctors.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(specialization__icontains=query)|
            Q(city__icontains=query)|
            Q(region__icontains=query)|
            Q(languages__icontains=query)
        )

    # Order by rating (descending)
    doctors = doctors.order_by('-rating')

    unique_years_of_experience = Doctor.objects.values_list('years_of_experience', flat=True).distinct()
    unique_cities= Doctor.objects.values_list('city', flat=True).distinct()

    context = {
        'doctors': doctors,
        'query': query,
        'city': city,
        'region': region,
        'years_of_experience': years_of_experience,
        'languages': languages,
        'doctor_type': doctor_type,
        'rating': rating,
        'unique_years_of_experience':unique_years_of_experience,
        'unique_cities':unique_cities,
    }

    return render(request, template, context)


def Posts(request):
    pass

def PatientAppointments(request):
    pass

def Doctors(request):
    pass

def Messages(request):
    pass

def DoctorLogout(request):
    logout(request)
    next_page = request.GET.get('next', 'DoctorLogin')
    return redirect(reverse(next_page))
    



# POSTS SECTION 
def PostList(request):
    posts = Post.objects.all().order_by('-published_date')
    context = {'posts': posts}
    return render(request, 'posts/post_list.html', context)

@login_required(login_url='login')
def MyPosts(request):
    doctor = Doctor.objects.get(user=request.user)
    posts = Post.objects.filter(author=doctor).order_by('-published_date')
    context = {'posts': posts}
    return render(request, 'posts/my_posts.html', context)


def PostDetail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    liked = post.has_liked(request.user)  # Check if user already liked

    if request.method == 'POST':
        form = ThumbsUpForm(request.POST)  # Handle form submission (if applicable)
        if form.is_valid():
            if not liked:
                # Add user to liked_by and increment thumbs_up
                post.liked_by.add(request.user)
                post.thumbs_up += 1
                post.save()
                messages.success(request, "Liked Successfully!")
                liked = True  # Update liked flag after thumbs up
            else:
                messages.error(request, "You already liked this post!")

    context = {'post': post, 'liked': liked}
    return render(request, 'posts/post_detail.html', context)


@login_required(login_url='login')
def CreatePost(request):
    doctor = Doctor.objects.get(user=request.user)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = doctor
            post.save()
            return redirect('post_detail', post_id=post.id)
    else:
        form = PostForm()

    return render(request, 'posts/create_post.html', {'form': form})

login_required(login_url='login')
def EditPost(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)

doctors/templates/posts/create_post.html
{% extends 'doctors/dashboard.html' %}
{% load static %}
{% block dashboard_content %}

<div class="bg-gray-200 font-[sans-serif] text-[#333]">
  <div class="min-h-screen flex flex-col items-center justify-center py-6 px-4">
    <div class="max-w-3xl w-full border py-8 px-6 rounded border-gray-300 bg-white">
      <a href="javascript:void(0)"><img src="{% static 'images/logo.png' %}" alt="logo" class='w-40 mb-10' /></a>
      {% if request.user.is_doctor %}
      <h1 class="text-center text-3xl font-extrabold text-gray-800">Welcome Dr. {{ request.user.doctor.first_name }}</h1>
      {% endif %}
      <h2 class="text-2xl text-center text-gray-700 mt-2">Create New Post</h2>

      <hr class="my-4">
      <form action="{% url 'create_post' %}" method="POST" enctype="multipart/form-data" class="mt-10 space-y-4">
        {% csrf_token %}
        <div class="flex flex-col items-center">
          <div class="flex justify-center">
            <div class="w-3/4">
              <div class="space-y-4">

                <label for="id_title" class="block text-sm font-medium text-gray-700">Title</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.title }}
                </div>

                <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.description }}
                </div>

                <label for="id_image_main" class="block text-sm font-medium text-gray-700">Main Image</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image_main }}
                </div>

                <label for="id_image1" class="block text-sm font-medium text-gray-700">Image 1</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image1 }}
                </div>

                <label for="id_image2" class="block text-sm font-medium text-gray-700">Image 2</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image2 }}
                </div>

                <label for="id_image3" class="block text-sm font-medium text-gray-700">Image 3</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image3 }}
                </div>

                <label for="id_content" class="block text-sm font-medium text-gray-700">Content</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.content }}
                </div>

              </div>
            </div>
          </div>
        </div>

        <div class="flex justify-center mt-6">
          <button type="submit" class="w-3/4 py-2.5 px-4 text-sm rounded text-center text-white bg-blue-500 hover:bg-blue-600 focus:outline-none transition duration-200">
            Create Post
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

doctors/templates/posts/edit_post.html
{% extends 'doctors/dashboard.html' %}
{% load static %}
{% block dashboard_content %}

<div class="bg-gray-200 font-[sans-serif] text-[#333]">
  <div class="min-h-screen flex flex-col items-center justify-center py-6 px-4">
    <div class="max-w-3xl w-full border py-8 px-6 rounded border-gray-300 bg-white">
      <a href="javascript:void(0)"><img src="{% static 'images/logo.png' %}" alt="logo" class='w-40 mb-10' /></a>
      {% if request.user.is_doctor %}
      <h1 class="text-center text-3xl font-extrabold text-gray-800">Welcome Dr. {{ request.user.doctor.first_name }}</h1>
      {% endif %}
      <h2 class="text-2xl text-center text-gray-700 mt-2">Edit Post</h2>

      <hr class="my-4">
      <form action="{% url 'edit_post' post.id %}" method="POST" enctype="multipart/form-data" class="mt-10 space-y-4">
        {% csrf_token %}
        <div class="flex flex-col items-center">
          <div class="flex justify-center">
            <div class="w-3/4">
              <div class="space-y-4">

                <label for="id_title" class="block text-sm font-medium text-gray-700">Title</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.title }}
                </div>

                <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.description }}
                </div>

                <label for="id_image_main" class="block text-sm font-medium text-gray-700">Main Image</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image_main }}
                </div>

                <label for="id_image1" class="block text-sm font-medium text-gray-700">Image 1</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image1 }}
                </div>

                <label for="id_image2" class="block text-sm font-medium text-gray-700">Image 2</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image2 }}
                </div>

                <label for="id_image3" class="block text-sm font-medium text-gray-700">Image 3</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.image3 }}
                </div>

                <label for="id_content" class="block text-sm font-medium text-gray-700">Content</label>
                <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  {{ form.content }}
                </div>

              </div>
            </div>
          </div>
        </div>

        <div class="flex justify-center mt-6">
          <button type="submit" class="w-3/4 py-2.5 px-4 text-sm rounded text-center text-white bg-blue-500 hover:bg-blue-600 focus:outline-none transition duration-200">
            Save Changes
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

doctors/templates/posts/my_posts.html
{% extends 'doctors/dashboard.html' %}
{% load static %}

{% block dashboard_content %}
<div class="lg:col-span-7 col-span-1 p-6 bg-gray-200 overflow-y-auto">
  <div class="container mx-auto p-6">
    <div class="bg-white shadow-md rounded-lg p-8">
      <div class="flex justify-between items-center mb-4">
        <h1 class="text-3xl font-bold text-gray-800">My Posts</h1>
        <a href="{% url 'create_post' %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300 font-bold">Create A New Post</a>
      </div>
      <div class="grid gap-6">
        {% for post in posts %}
        <div class="bg-gray-100 shadow-sm rounded-lg p-6 flex flex-col md:flex-row items-center">
          <div class="w-full md:w-2/3">
            <h2 class="text-xl font-bold text-gray-800 mb-2">{{ post.title }}</h2>
            <p class="text-gray-600 mb-4">{{ post.description }}</p>
            <div class="flex space-x-4">
              <a href="{% url 'edit_post' post.id %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300 font-bold">Edit Post</a>
              <a href="{% url 'delete_post' post.id %}" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-300 font-bold">Delete Post</a>
            </div>
          </div>
          <div class="w-full md:w-1/3 mt-4 md:mt-0 md:ml-6">
            <img src="{{ post.image_main.url }}" class="w-full rounded" alt="Post Main Image">
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

doctors/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="bg-gray-800 pt-12">
  <div class="container  mx-auto py-12">
    <div class="bg-white shadow rounded-lg p-8">
      <div class="flex flex-col md:flex-row items-start">
        <div class="md:w-3/4 mr-4">
          <a href="{{ request.META.HTTP_REFERER }}" class="text-blue-800 hover:text-blue-700 mb-4 inline-block">
            <i class="fas fa-arrow-left mr-2"></i> Back 
          </a>
          <h1 class="text-3xl font-bold mb-4">{{ post.title }}</h1>
          <div class="flex items-center mb-4">
            <p class="text-gray-600 mr-2">Published: {{ post.published_date| date:"N d, Y" }}</p>
          </div>
          <div class="post-content w-full prose mb-8">
            <!-- Main post content -->
            {{ post.content }}
          </div>
        </div>
        <div class="md:w-1/4 mt-8 md:mt-0">
          <!-- Main post image -->
          <img src="{{ post.image_main.url }}" class="w-full mb-4 rounded-lg" alt="Post Image">
        </div>
      </div>

      <!-- Additional images -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {% if post.image1 %}
        <div>
          <img src="{{ post.image1.url }}" class="w-full rounded-lg" alt="Image 1">
        </div>
        {% endif %}
        {% if post.image2 %}
        <div>
          <img src="{{ post.image2.url }}" class="w-full rounded-lg" alt="Image 2">
        </div>
        {% endif %}
        {% if post.image3 %}
        <div>
          <img src="{{ post.image3.url }}" class="w-full rounded-lg" alt="Image 3">
        </div>
        {% endif %}
      </div>

      {% if request.user.is_authenticated %}
      <form method="POST" class="flex items-center mt-8">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary ml-2">
          <img src="{% static 'images/thumbs-up.png' %}" width="40px" alt="posts">
        </button>
      </form>
      {% else %}
      <p class="text-gray-600 mt-8">You need to be logged in to like a post.</p>
      {% endif %}

      {% if messages %}
      <ul class="list-disc space-y-2 text-gray-600 mt-4">
        {% for message in messages %}
        <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

doctors/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="bg-gray-800 pt-12 px-10 py-12">
  <div class="container mx-auto py-12 mb-24 ">
    <div class="bg-white shadow rounded-lg p-8 pb-12">
      <div class="flex flex-col  md:flex-row items-center">
        <div class="md:w-3/4 mr-4 items-center">
          <a href="{% url 'home' %}" class="text-gray-500 hover:text-blue-700 mb-4 inline-block">
            <i class="fas fa-arrow-left mr-2"></i> Back
          </a>

        <div class="container mx-auto p-4">
          <ul class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for post in posts %}
              <li class="bg-white shadow rounded-lg overflow-hidden">
                <a href="{% url 'post_detail' post.id %}">
                  <img src="{{ post.image_main.url }}" alt="Property Image" class="w-full h-48 object-cover rounded-t-lg">
                  <div class="p-4">
                      <h3 class="text-xl font-semibold mb-2">
                          {{ post.title }}
                      </h3>
                  </a>
                  <p class="text-gray-600 mb-2">{{ post.description }}</p>
                  <p class="text-gray-500 mb-2">Published: {{ post.published_date }}</p>
                  <div class="flex items-center">
                    <img src="{% static 'images/thumbs-up.png' %}" width="40px" alt="posts">                    
                    <span class="ml-2">{{ post.thumbs_up }}</span>
                  </div>
                </div>
              </li>
            {% endfor %}
          </ul>
        </div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}