Digitalhealthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#static files and media files configuration
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('Patients/', include('patients.urls')),
    path('Doctors/', include('doctors.urls')),
    path('Appointments/', include('appointments.urls')),
    path('Rating/', include('rating.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointments/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('schedule_appointment/<int:doctor_id>/', views.ScheduleAppointment, name='schedule_appointment'),
    path('view_doctor_appointments/', views.ViewMyDoctorAppointments, name='view_doctor_appointments'),
    path('view_patient_appointments/', views.ViewMyPatientAppointments, name='view_patient_appointments'),
    path('join_the_call/<int:appointment_id>', views.JoinTheCall, name='join_the_call'),
    path('delete_appointment/<int:appointment_id>/', views.DeleteAppointment, name='delete_appointment'),
    path('edit_appointment/<int:appointment_id>/', views.EditAppointment, name='edit_appointment'),
    path('confirm_appointment/<int:appointment_id>/', views.ConfirmAppointment, name='confirm_appointment'),
    path('reschedule_appointment/<int:appointment_id>/', views.RescheduleAppointment, name='reschedule_appointment'),
    path('VideoCall/<int:appointment_id>/', views.StartVideoCall, name='start_video_call'),
]

doctors/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.dashboard, name="dashboard"),
    path('DoctorProfile/', views.DoctorProfile, name="DoctorProfile"),
    path('DoctorSignUp/', views.registerDoctor, name="DoctorSignUp"),
    path('DoctorLogin/', views.DoctorLogin, name="DoctorLogin"),
    path('DoctorLogout/', views.DoctorLogout, name="DoctorLogout"),
    path('BrowseDoctors/', views.BrowseDoctors, name="BrowseDoctors"),
    path('DoctorDetail/<int:pk>', views.DoctorDetail, name="doctor_detail"),


    path('Posts/', views.PostList, name='post_list'),
    path('Posts/MyPosts', views.MyPosts, name='my_posts'),
    path('Posts/PostDetail/<int:post_id>/', views.PostDetail, name='post_detail'),
    path('Posts/CreatePost/', views.CreatePost, name='create_post'),
    path('Posts/EditPost/<int:post_id>/', views.EditPost, name='edit_post'),
    path('Posts/DeletePost/<int:post_id>/', views.DeletePost, name='delete_post'),
    path('activate/<uidb64>/<token>/',views.activateAccount , name='activate'),

]

rating/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('rate_doctor/<int:doctor_id>/', views.RateDoctor, name = 'rate_doctor'),        
]

appointments/models.py
from django.db import models
from django.contrib.auth.models import User
from doctors.models import Doctor
from patients.models import Patient

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_appointments')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor_appointments')
    appointment_date = models.DateTimeField()
    
    status = models.CharField(max_length=20, choices=(
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('declined', 'Declined'),
        ('rescheduled', 'Rescheduled'),
        ('completed', 'Completed'),
    ), default='pending')
    additional_requests = models.CharField(max_length=500, null=True, blank=True)
    video_call_link = models.CharField(max_length=200, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Appointment with {self.doctor.user.username} on {self.appointment_date}"

doctors/models.py
from django.db import models
from django.contrib.auth.models import User



class Doctor(models.Model):
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)

    # verification status
    VERIFICATION_STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('declined', 'Declined'),
    )
    verification_message = models.TextField(max_length=1000, blank=True, null=True, default="")
    verification_status = models.CharField(max_length=20, choices=VERIFICATION_STATUS_CHOICES, blank=True, null=True)

    # verification details
    national_id_or_passport_image = models.ImageField(upload_to='doctors/verification', blank=True, null=True)
    phone_number = models.CharField(max_length=14, default=True, blank=True, null=True)
    photo = models.ImageField(upload_to='doctors/account', null=True, blank=True)
    medical_licence = models.ImageField(upload_to='doctors/verification', null=True, blank=True)
    passport_or_id_number = models.CharField(max_length=20, blank=True, null=True)
    date_issued = models.DateField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)

    # specialization
    specialization = models.CharField(max_length=1000, blank=True, null=True, default="")


    city = models.CharField(max_length=100,  blank=True, null=True)

    REGION_CHOICES = (
        ("Afar", "Afar"),
        ("Amhara", "Amhara"),
        ("Benishangul-Gumuz", "Benishangul-Gumuz"),
        ("Gambela", "Gambela"),
        ("Harari", "Harari"),
        ("Oromia", "Oromia"),
        ("Somali", "Somali"),
        ("Southern Nations, Nationalities, and Peoples'", "Southern Nations, Nationalities, and Peoples'"),
        ("Tigray", "Tigray"),
        ("Sidama", "Sidama"),
        ("Nuer", "Nuer"),
        ("Wolayita", "Wolayita"),
    )
    region = models.CharField(max_length=100, choices=REGION_CHOICES, blank=True, null=True)

    country = models.CharField(max_length=100, blank=True, null=True)

    # Years of experience
    YEARS_OF_EXPERIENCE_CHOICES = (
        ("less than 1", "Less than 1 year"),
        ("1-3", "1-3 years"),
        ("3-5", "3-5 years"),
        ("more than 5", "More than 5 years"),
    )
    years_of_experience = models.CharField(max_length=20, choices=YEARS_OF_EXPERIENCE_CHOICES, blank=True, null=True)

    # Languages
    languages = models.CharField(max_length=200, blank=True, null=True)
    

    # ratings
    rating = models.FloatField(default=0.0, null=True, blank=True)
    rating_counter = models.IntegerField(default=0, null=True, blank=True)

   
    def __str__(self):
        return f"Dr. {self.first_name} {self.last_name}"



class Post(models.Model):
    author = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    image_main = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    image1 = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    image2 = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    image3 = models.ImageField(upload_to='images/posts', null=True, blank=True, default='images/posts/default.jpg')
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    thumbs_up = models.PositiveIntegerField(default=0)
    liked_by = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def has_liked(self, user):
        return user in self.liked_by.all()  
    
    def __str__(self):
        return self.title

patients/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime 
from doctors.models import Doctor


# Create your models here.
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fname = models.CharField(max_length=100)
    lname  = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    date_of_birth = models.DateField(null=True)
    age= models.IntegerField(null=True)
    gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female')], null=True)
    contact_number = models.CharField(max_length=15, null=True)
    address = models.TextField(null=True)
    emergency_contact_name = models.CharField(max_length=100, null=True)
    emergency_contact_phone = models.CharField(max_length=15, null=True)


    def create_user(self):
        pass
    
    def save(self, *args, **kwargs):
        if self.date_of_birth:
            today = datetime.date.today()
            age = today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
            self.age = age
        super().save(*args, **kwargs)

    def __str__(self):
        return self.fname + " " + self.lname

class MedicalHistory(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='medical_histories')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='patient_medical_histories', null=True, blank=True)
    diagnosis = models.TextField(null=True, blank=True)
    symptoms = models.TextField(null=True, blank=True)
    treatment = models.TextField(null=True, blank=True)
    prescription = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Medical History for {self.patient.fname} {self.patient.lname}"

appointments/forms.py
from django import forms
from .models import Appointment
import datetime 
from django.utils import timezone



class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            'appointment_date',
            'additional_requests',            
        ]
        widgets = {
            'appointment_date': forms.DateTimeInput(attrs={'type': 'date'})
            }
        



def clean_appointment_date(self):
    appointment_date = self.cleaned_data['appointment_date'].replace(tzinfo=None)
    now = datetime.datetime.now()
    if appointment_date < now:
        raise forms.ValidationError("Appointment date can't be set in the past.")
    return appointment_date

class RescheduleAppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            'appointment_date',
        ]
        widgets = {
            'appointment_date': forms.DateTimeInput(attrs={'type': 'date'})
            }
        



def clean_appointment_date(self):
    appointment_date = self.cleaned_data['appointment_date'].replace(tzinfo=None)
    now = datetime.datetime.now()
    if appointment_date < now:
        raise forms.ValidationError("Appointment date can't be set in the past.")
    return appointment_date

appointments/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .models import Appointment
from doctors.models import Doctor
from patients.models import Patient
from .forms import AppointmentForm, RescheduleAppointmentForm
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings



def ScheduleAppointment(request, doctor_id):
    if not request.user.is_authenticated:
        messages.error(request, "You need to login before scheduling an appointment!")
        return redirect('PatientLogin')
    doctor = get_object_or_404(Doctor, id=doctor_id)
    patient = get_object_or_404(Patient, user=request.user)
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.patient = patient
            appointment.doctor = doctor
            appointment.appointment_date = form.cleaned_data['appointment_date']
            appointment.additional_requests = form.cleaned_data['additional_requests']
            appointment.save()
            messages.success(request, "Appointment Scheduled Successfully")
            return redirect('view_doctor_appointments')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
    else:
        form = AppointmentForm()
    return render(request, 'patients/schedule_appointment.html', {'form': form, 'doctor': doctor})


@login_required
def ViewMyPatientAppointments(request):
    doctor = get_object_or_404(Doctor, user=request.user)
    appointments = Appointment.objects.filter(doctor=doctor).order_by('-appointment_date')

    return render(request, 'doctors/patient_appointments.html', {'appointments': appointments, 'doctor': doctor})

@login_required
def ViewMyDoctorAppointments(request):
    patient = get_object_or_404(Patient, user=request.user)
    appointments = Appointment.objects.filter(patient=patient).order_by('-appointment_date')

    return render(request, 'patients/doctor_appointments.html', {'appointments': appointments})

@login_required
def DeleteAppointment(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.delete()
    messages.success(request, "Appointment Deleted Successfully")
    return redirect('view_doctor_appointments')



@login_required
def RescheduleAppointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        form = RescheduleAppointmentForm(request.POST)
        if form.is_valid():
            appointment.appointment_date = form.cleaned_data['appointment_date']
            appointment.save()
            messages.success(request, "Appointment Rescheduled Successfully!")
            return redirect('view_patient_appointments')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
    else:
        form = RescheduleAppointmentForm()
    
    return render(request, 'doctors/reschedule_appointment.html', {'form': form})

@login_required
def EditAppointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment.appointment_date = form.cleaned_data['appointment_date']
            appointment.additional_requests = form.cleaned_data['additional_requests']
            appointment.save()
            messages.success(request, "Appointment Edited Successfully!")
            return redirect('view_doctor_appointments')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
    else:
        form = AppointmentForm()
    
    return render(request, 'patients/edit_appointment.html', {'form': form})


@login_required
def StartVideoCall(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    room_id = str(appointment.id) 

    if(Doctor.objects.filter(user=request.user).exists()):
        doc = Doctor.objects.get(user=request.user)
        template_name = 'doctors/dashboard.html'
        full_name = f"Dr. {doc.first_name} {doc.last_name}"    
    else:
        template_name = 'patients/dashboard.html'
        full_name = f"{request.user}"    
    
    print(template_name)

    return render(request, 'communication/video_call.html', {'full_name': full_name, 'room_id':room_id, 'template_name':template_name})
    
@login_required
def JoinTheCall(request, appointment_id):
    roomID = str(appointment_id)
    meeting_link = f'http://localhost:8000/Appointments/VideoCall/{roomID}/?roomID={roomID}'
    return redirect(meeting_link)

    

@login_required
def ConfirmAppointment(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.status = 'accepted'

    # Generate the video call link
    doc = Doctor.objects.get(user=request.user)
    full_name = f"Dr. {doc.first_name} {doc.last_name}"
    room_id = str(appointment.id)  # Use the appointment ID as the room ID
    # video_call_link = f"{request.scheme}://{request.get_host()}/video_call/?roomID={room_id}"
    # video_call_link = f"http://localhost:8000/Appointments/VideoCall/13/?roomID=3832"
    video_call_link = f"http://localhost:8000/Appointments/VideoCall/14/?roomID={room_id}"
    appointment.video_call_link = video_call_link

    appointment.save()


    # Send an email to the patient with the video call link
    patient_email = appointment.patient.user.email
    subject = "Video Call Link for Your Appointment"
    message = f"Dear {appointment.patient.user.first_name},\n\n"
    message += f"{full_name} has confirmed your appointment.\n"
    message += f"Please click the following link to join the video call:\n"
    message += f"{video_call_link}\n\n"
    message += "Best regards,\n"
    message += "MediConnect Team"

    send_mail(
        subject,
        message,
        settings.DEFAULT_FROM_EMAIL,
        [patient_email],
        fail_silently=False,
    )

    messages.success(request, "Appointment Accepted Successfully")
    return redirect('view_patient_appointments')

appointments/templates/doctors/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="min-h-screen flex flex-col lg:flex-row">
  <!-- Burger menu for small screens -->
  <div class="bg-gray-800 text-white w-full lg:hidden">
    <div class="flex items-center justify-between p-4">
      <img src="{% static 'assets/images/logooo.png' %}" alt="logo" class="w-32">
      <button id="burger-menu" class="text-white focus:outline-none">
        <ion-icon name="menu-outline" size="large"></ion-icon>
      </button>
    </div>
  </div>

  <!-- Sidebar -->
  <div id="sidebar" class="bg-gray-800 text-white w-64 flex-shrink-0 hidden lg:block fixed lg:relative top-0 left-0 h-full lg:h-auto z-50 lg:z-auto">
    <div class="flex items-center justify-center py-6">
      <img src="{% static 'images/logo.png' %}" alt="logo" class="w-32">
    </div>
    <nav class="mt-10">
      <a href="{% url 'DoctorProfile' %}" class="flex items-center p-2 text-sm font-medium rounded-lg hover:bg-gray-200 transition">
        <ion-icon name="person-circle"></ion-icon>
        <span class="ml-3">My profile</span>
      </a>
      <a href="{% url 'DoctorProfile' %}" class="flex items-center p-2 text-sm font-medium rounded-lg hover:bg-gray-200 transition">
        <ion-icon name="pencil"></ion-icon>
        <span class="ml-3">Appointments</span>
      </a>

      <a href="{% url 'DoctorProfile' %}" class="flex items-center p-2 text-sm font-medium rounded-lg hover:bg-gray-200 transition">
        <ion-icon name="checkmark-circle"></ion-icon>
        <span class="ml-3">Chats</span>
      </a>
      
      <a href="{% url 'BrowseDoctors' %}" class="flex items-center p-2 text-sm font-medium rounded-lg hover:bg-gray-200 transition">
        <ion-icon name="book"></ion-icon>
        <span class="ml-3">Search Doctors</span>
      </a>
      <a href="{% url 'DoctorProfile' %}" class="flex items-center p-2 text-sm font-medium rounded-lg hover:bg-gray-200 transition">
        <ion-icon name="book"></ion-icon>
        <span class="ml-3">Posts</span>
      </a>
      <a href="{% url 'DoctorLogout' %}" class="flex items-center p-2 text-sm font-medium rounded-lg hover:bg-gray-200 transition">
        <ion-icon name="book"></ion-icon>
        <span class="ml-3">Log Out</span>
      </a>

      
    </nav>
  </div>

  <!-- Main content -->
  <div class="flex-grow bg-gray-100 p-6">
    {% block dashboard_content %}
    <!-- Placeholder for actual content -->
    {% endblock %}
  </div>
</div>

<script>
  document.getElementById('burger-menu').addEventListener('click', function() {
    const sidebar = document.getElementById('sidebar');
    sidebar.classList.toggle('hidden');
  });
</script>
{% endblock %}

appointments/templates/doctors/doctor_profile.html
{% extends 'doctors/dashboard.html' %}
{% load static %}
{% block dashboard_content %}


<div class="bg-gray-200 font-[sans-serif] text-[#333]">
  <div class="min-h-screen flex flex-col items-center justify-center py-6 px-4">
    <div class="max-w-3xl w-full border py-8 px-6 rounded border-gray-300 bg-white">
      <a href="javascript:void(0)"><img src="{% static 'images/logo.png' %}" alt="logo" class='w-40 mb-10' /></a>
      <h1 class="text-center text-3xl font-extrabold text-gray-800">Welcome Dr. {{ doc.first_name }}</h1>
      <h2 class="text-2xl text-center text-gray-700 mt-2">Edit Your Profile</h2>

      <hr class="my-4">
      <form action="{% url 'DoctorProfile' %}" method="POST" enctype="multipart/form-data" class="mt-10 space-y-4">
        {% csrf_token %}
        <div class="flex flex-col items-center">
          <div class="flex flex-col items-center">
          
            {% if doc.photo %}
            <div class="w-58 h-58 rounded-full mb-4" >
              <label for="id_profile_picture" class="profile-picture-label">
                <img src="{{ doc.photo.url }}" class="w-48 h-48 rounded-full mb-4" alt="User Image">
                <div class="ml-24 text-sm -mt-3 mb-4 flex text-center items-center">
                  <ion-icon class="gray-600" name="pencil"></ion-icon>
                </div>
              </div>
              {% endif %}
              
            </div>            
          </div>
          
          <div class="flex justify-center">
            <div class="w-3/4">
              <div class="space-y-4">
                
                <h5 class="text-2xl text-center text-gray-700 mt-2">Personal Information</h5>
              <label for="first_name" class="block text-sm font-medium text-gray-700">First Name</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.first_name }}
              </div>

              <label for="last_name" class="block text-sm font-medium text-gray-700">Last Name</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.last_name }}
              </div>

              <label for="id_date_of_birth" class="block text-sm font-medium text-gray-700">Date of Birth</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.date_of_birth }}
              </div>
              
              <label for="id_languages" class="block text-sm font-medium text-gray-700">Spoken Languages</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.languages }}
              </div>
              
              <label for="id_photo" class="block text-sm font-medium text-gray-700">Profile Picture</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.photo }}
              </div>

              <label for="id_passport_or_id_number" class="block text-sm font-medium text-gray-700">Passport or National ID Number</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.passport_or_id_number }}
              </div>

              <label for="id_national_id_or_passport_image" class="block text-sm font-medium text-gray-700">Passport or National ID Image</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.national_id_or_passport_image }}
              </div>
                           

              <label for="id_date_issued" class="block text-sm font-medium text-gray-700">Date Issued</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.date_issued }}
              </div>

              <label for="id_expiry_date" class="block text-sm font-medium text-gray-700">Expiry Date</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.expiry_date }}
              </div>

             
              <h5 class="text-2xl text-center text-gray-700 mt-2">Career Information</h5>
            
              <label for="id_specialization" class="block text-sm font-medium text-gray-700">Specialization</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.specialization }}
              </div>

              <label for="id_medical_licence" class="block text-sm font-medium text-gray-700">Medical Licence</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.medical_licence }}
              </div>
              
              <label for="id_years_of_experience" class="block text-sm font-medium text-gray-700">Years of Experience</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.years_of_experience }}
              </div>
              
    
              
              <h5 class="text-2xl text-center text-gray-700 mt-2">Address and Contact Information</h5>
              
              <label for="id_region" class="block text-sm font-medium text-gray-700">Region</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.region }}
              </div>

              <label for="id_city" class="block text-sm font-medium text-gray-700">City</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.city }}
              </div>

              <label for="id_phone_number" class="block text-sm font-medium text-gray-700">Phone Number</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.phone_number }}
              </div>

              <label for="id_email" class="block text-sm font-medium text-gray-700">Active Email</label>
              <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                {{ form.email}}
              </div>




            </div>
          </div>
        </div>
        
        <div class="flex justify-center mt-6">
          <button type="submit" class="w-3/4 py-2.5 px-4 text-sm rounded text-center text-white bg-blue-500 hover:bg-blue-600 focus:outline-none transition duration-200">
            Save
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

appointments/templates/doctors/reschedule_appointment.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="bg-gray-200 font-[sans-serif] text-[#333]">
  <div class="min-h-screen flex flex-col items-center justify-center py-6 px-4">
    <div class="max-w-3xl w-full border py-8 px-6 rounded border-gray-300 bg-white">
      <a href="javascript:void(0)"><img src="{% static 'assets/images/logo.png' %}" alt="logo" class='w-40 mb-10' /></a>
 
      

    <form method="post" class="space-y-4">
      {% csrf_token %}
      <h1 class=" text-2xl font-extrabold text-gray-800">Reschedule Appointment</h1>

      <div class="space-y-4">
        <label for="id_address" class="block text-sm font-medium text-gray-700">{{form.appointment_date.label}}</label>
        <input type="datetime-local" name="appointment_date" value="{{ form.appointment_date.value|date:'c' }}">
      </div>

      <div class="flex items-center">
        <button type="submit" class="btn bg-blue-500 text-white items-cen hover:bg-blue-700 px-4 py-2 rounded">
          Reschedule
        </button>
      </div>
    </form>
  </div>
</div>
</section>

{% endblock %}