Digitalhealthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#static files and media files configuration
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('Patients/', include('patients.urls')),
    path('Doctors/', include('doctors.urls')),
    path('Appointments/', include('appointments.urls')),
    path('Rating/', include('rating.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointments/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('schedule_appointment/<int:doctor_id>/', views.ScheduleAppointment, name='schedule_appointment'),
    path('view_doctor_appointments/', views.ViewMyDoctorAppointments, name='view_doctor_appointments'),
    path('view_patient_appointments/', views.ViewMyPatientAppointments, name='view_patient_appointments'),
    path('join_the_call/<int:appointment_id>', views.JoinTheCall, name='join_the_call'),
    path('delete_appointment/<int:appointment_id>/', views.DeleteAppointment, name='delete_appointment'),
    path('edit_appointment/<int:appointment_id>/', views.EditAppointment, name='edit_appointment'),
    path('confirm_appointment/<int:appointment_id>/', views.ConfirmAppointment, name='confirm_appointment'),
    path('reschedule_appointment/<int:appointment_id>/', views.RescheduleAppointment, name='reschedule_appointment'),
    path('VideoCall/<int:appointment_id>/', views.StartVideoCall, name='start_video_call'),
]

patients/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="PatientHome"),
    path('PatientDashboard/<int:pk>', views.PatientDashboard, name="PatientDashboard"),
    path('PatientProfile/', views.PatientProfile, name="PatientProfile"),
    path('PatientSignUp/', views.PatientSignUp, name="PatientSignUp"),
    path('PatientLogin/', views.PatientLogin, name="PatientLogin"),
    path('Posts/<int:pk>', views.Posts, name="Posts"),
    path('PatientAppointments/<int:pk>', views.PatientAppointments, name="PatientAppointments"),
    path('Doctors/<int:pk>', views.Doctors, name="Doctors"),
    path('Messages/<int:pk>', views.Messages, name="Messages"),
    path('PatientLogout/', views.PatientLogout, name="PatientLogout"),
    path('GeminiChat/', views.GeminiChat, name="GeminiChat"),
    path('medical-history/<int:patient_id>', views.view_medical_history, name='view_medical_history'),
    path('add-diagnostic-results/<int:patient_id>', views.add_diagnostic_results, name='add_diagnostic_results'),
]

rating/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('rate_doctor/<int:doctor_id>/', views.RateDoctor, name = 'rate_doctor'),        
]

appointments/models.py
from django.db import models
from django.contrib.auth.models import User
from doctors.models import Doctor
from patients.models import Patient

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_appointments')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor_appointments')
    appointment_date = models.DateTimeField()
    
    status = models.CharField(max_length=20, choices=(
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('declined', 'Declined'),
        ('rescheduled', 'Rescheduled'),
        ('completed', 'Completed'),
    ), default='pending')
    additional_requests = models.CharField(max_length=500, null=True, blank=True)
    video_call_link = models.CharField(max_length=200, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Appointment with {self.doctor.user.username} on {self.appointment_date}"

patients/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime 
from doctors.models import Doctor


# Create your models here.
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fname = models.CharField(max_length=100)
    lname  = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    date_of_birth = models.DateField(null=True)
    age= models.IntegerField(null=True)
    gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female')], null=True)
    contact_number = models.CharField(max_length=15, null=True)
    address = models.TextField(null=True)
    emergency_contact_name = models.CharField(max_length=100, null=True)
    emergency_contact_phone = models.CharField(max_length=15, null=True)


    def create_user(self):
        pass
    
    def save(self, *args, **kwargs):
        if self.date_of_birth:
            today = datetime.date.today()
            age = today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
            self.age = age
        super().save(*args, **kwargs)

    def __str__(self):
        return self.fname + " " + self.lname

class MedicalHistory(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='medical_histories')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='patient_medical_histories', null=True, blank=True)
    diagnosis = models.TextField(null=True, blank=True)
    symptoms = models.TextField(null=True, blank=True)
    treatment = models.TextField(null=True, blank=True)
    prescription = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Medical History for {self.patient.fname} {self.patient.lname}"

appointments/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .models import Appointment
from doctors.models import Doctor
from patients.models import Patient
from .forms import AppointmentForm, RescheduleAppointmentForm
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings



def ScheduleAppointment(request, doctor_id):
    if not request.user.is_authenticated:
        messages.error(request, "You need to login before scheduling an appointment!")
        return redirect('PatientLogin')
    doctor = get_object_or_404(Doctor, id=doctor_id)
    patient = get_object_or_404(Patient, user=request.user)
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.patient = patient
            appointment.doctor = doctor
            appointment.appointment_date = form.cleaned_data['appointment_date']
            appointment.additional_requests = form.cleaned_data['additional_requests']
            appointment.save()
            messages.success(request, "Appointment Scheduled Successfully")
            return redirect('view_doctor_appointments')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
    else:
        form = AppointmentForm()
    return render(request, 'patients/schedule_appointment.html', {'form': form, 'doctor': doctor})


@login_required
def ViewMyPatientAppointments(request):
    doctor = get_object_or_404(Doctor, user=request.user)
    appointments = Appointment.objects.filter(doctor=doctor).order_by('-appointment_date')

    return render(request, 'doctors/patient_appointments.html', {'appointments': appointments, 'doctor': doctor})

@login_required
def ViewMyDoctorAppointments(request):
    patient = get_object_or_404(Patient, user=request.user)
    appointments = Appointment.objects.filter(patient=patient).order_by('-appointment_date')

    return render(request, 'patients/doctor_appointments.html', {'appointments': appointments})

@login_required
def DeleteAppointment(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.delete()
    messages.success(request, "Appointment Deleted Successfully")
    return redirect('view_doctor_appointments')



@login_required
def RescheduleAppointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        form = RescheduleAppointmentForm(request.POST)
        if form.is_valid():
            appointment.appointment_date = form.cleaned_data['appointment_date']
            appointment.save()
            messages.success(request, "Appointment Rescheduled Successfully!")
            return redirect('view_patient_appointments')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
    else:
        form = RescheduleAppointmentForm()
    
    return render(request, 'doctors/reschedule_appointment.html', {'form': form})

@login_required
def EditAppointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment.appointment_date = form.cleaned_data['appointment_date']
            appointment.additional_requests = form.cleaned_data['additional_requests']
            appointment.save()
            messages.success(request, "Appointment Edited Successfully!")
            return redirect('view_doctor_appointments')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{error}")
    else:
        form = AppointmentForm()
    
    return render(request, 'patients/edit_appointment.html', {'form': form})


@login_required
def StartVideoCall(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    room_id = str(appointment.id) 

    if(Doctor.objects.filter(user=request.user).exists()):
        doc = Doctor.objects.get(user=request.user)
        template_name = 'doctors/dashboard.html'
        full_name = f"Dr. {doc.first_name} {doc.last_name}"    
    else:
        template_name = 'patients/dashboard.html'
        full_name = f"{request.user}"    
    
    print(template_name)

    return render(request, 'communication/video_call.html', {'full_name': full_name, 'room_id':room_id, 'template_name':template_name})
    
@login_required
def JoinTheCall(request, appointment_id):
    roomID = str(appointment_id)
    meeting_link = f'http://localhost:8000/Appointments/VideoCall/{roomID}/?roomID={roomID}'
    return redirect(meeting_link)

    

@login_required
def ConfirmAppointment(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.status = 'accepted'

    # Generate the video call link
    doc = Doctor.objects.get(user=request.user)
    full_name = f"Dr. {doc.first_name} {doc.last_name}"
    room_id = str(appointment.id)  # Use the appointment ID as the room ID
    # video_call_link = f"{request.scheme}://{request.get_host()}/video_call/?roomID={room_id}"
    # video_call_link = f"http://localhost:8000/Appointments/VideoCall/13/?roomID=3832"
    video_call_link = f"http://localhost:8000/Appointments/VideoCall/14/?roomID={room_id}"
    appointment.video_call_link = video_call_link

    appointment.save()


    # Send an email to the patient with the video call link
    patient_email = appointment.patient.user.email
    subject = "Video Call Link for Your Appointment"
    message = f"Dear {appointment.patient.user.first_name},\n\n"
    message += f"{full_name} has confirmed your appointment.\n"
    message += f"Please click the following link to join the video call:\n"
    message += f"{video_call_link}\n\n"
    message += "Best regards,\n"
    message += "MediConnect Team"

    send_mail(
        subject,
        message,
        settings.DEFAULT_FROM_EMAIL,
        [patient_email],
        fail_silently=False,
    )

    messages.success(request, "Appointment Accepted Successfully")
    return redirect('view_patient_appointments')

patients/views.py
from django import forms
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from .models import *
from . import gemini
from .forms import PatientForm, UserForm, UserLoginForm, GeminiChatForm, PatientProfileForm, MedicalHistoryForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def index(request):
    return HttpResponse("index home")

def PatientDashboard(request, pk):
    patient = get_object_or_404(Patient, user__pk=pk)
    context = {
        'patient' : patient 
    }
    
    return render(request, 'patients/dashboard.html', context)

def PatientProfile(request):
    curr_patient=get_object_or_404(Patient, user=request.user)
    if request.method == 'POST':
        form = PatientProfileForm(request.POST, request.FILES, instance=curr_patient)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully.')
            return redirect('PatientProfile')
    else:
        form = PatientProfileForm(instance=curr_patient)

    return render(request, 'patients/patient_profile.html', {'form': form,'pat': curr_patient})


def PatientSignUp(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        patient_form = PatientForm(request.POST)

        if patient_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()

            patient = patient_form.save(commit=False)
            patient.user = user
            patient.email = user_form.cleaned_data.get('email')
            patient.password = user_form.cleaned_data.get('password1')
            patient.save()

            patient_form = PatientForm(request.POST, instance=user.patient)
            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username = user.username, password = raw_password)
            login(request, user)
            chat = gemini.Chat()
            request.session['chat'] = chat.serialize()
            return redirect('PatientDashboard', pk = user.pk) 
    else:
        patient_form = PatientForm()
        user_form = UserForm()
    return render(request, 'patients/PatientSignUp.html', {'user_form':user_form, 'patient_form': patient_form})


def PatientLogin(request):
    if request.method == 'POST':
        user_form  = UserLoginForm(request.POST)

        if user_form.is_valid():
            user = user_form.get_user()
            if user is not None:
                login(request, user)
                chat = gemini.Chat()
                request.session['chat'] = chat.serialize()
                return redirect('PatientProfile')
    else:
        user_form  = UserLoginForm()
    
    return render(request, 'patients/patient_login.html', {'user_form':user_form})
                

def GeminiChat(request):
    if request.method == 'POST':
        chat_form = GeminiChatForm(request.POST)
        if chat_form.is_valid():
            chat_data = request.session.get('chat')
            if chat_data:
                chat = gemini.Chat.deserialize(chat_data)
                if len(chat.messages) == 0:
                    rep = chat.gemini_new_request(chat_form.cleaned_data.get('question'))
                else:
                    rep = chat.gemini_request(chat_form.cleaned_data.get('question'))

                request.session['chat'] = chat.serialize()
            return JsonResponse({'response' :rep})
    else:
        chat_form = GeminiChatForm()
    
    return render(request, 'patients/base.html', {'chat_form': chat_form})


def view_medical_history(request, patient_id):
    patient = get_object_or_404(Patient, id=patient_id)
    medical_histories = patient.medical_histories.all()
    return render(request, 'Medical_History/medical_history.html', {'patient': patient, 'medical_histories': medical_histories})


@login_required
def add_diagnostic_results(request, patient_id):
    doctor = Doctor.objects.get(user=request.user)
    patient = get_object_or_404(Patient, id=patient_id)
    if request.method == 'POST':
        form = MedicalHistoryForm(request.POST)
        if form.is_valid():
            medical_history = form.save(commit=False)
            medical_history.patient = patient
            medical_history.doctor = doctor
            medical_history.save()
            return redirect('view_medical_history', patient_id=patient.id)
    else:
        form = MedicalHistoryForm()
    return render(request, 'Medical_History/add_diagnostic_results.html', {'form': form, 'patient': patient})









def Posts(request):
    pass

def PatientAppointments(request):
    pass

def Doctors(request):
    pass

def Messages(request):
    pass

def PatientLogout(request):
    logout(request)
    next_page = request.GET.get('next', 'PatientLogin')
    return redirect(reverse(next_page))
    

appointments/templates/patients/doctor_appointments.html
{% extends 'patients/dashboard.html' %}
{% load static %}

{% block dashboard_content %}

  <div class="lg:col-span-7 col-span-1 p-6 bg-gray-200 overflow-y-auto">
    <div class="container mx-auto p-6">
      <div class="bg-white shadow-md rounded-lg p-8">
        <h1 class="text-3xl font-bold text-gray-800 mb-4">Appointments</h1>
        <div class="grid gap-6">
          {% for apt in appointments %}

          <div class="bg-gray-100 shadow-sm rounded-lg p-6 flex flex-col md:flex-row items-center">
            <div class="w-full md:w-2/3">
              <div class="text-gray-600 mb-1">Appointment Date {{ apt.appointment_date }}</div>
              <div class="text-gray-600 mb-1">Requested on {{ apt.created_at  }}</div>
              <div class="text-gray-600 mb-1">Doctor {{ apt.doctor }}</div>
              <div class="text-gray-600 mb-4">Status: {{ apt.status }}</div>




              {% if apt.status == 'accepted' %}

              <p class="text-xl font-semibold text-green-700 mb-2">Your Appontment has been Confirmed by Dr. {{apt.doctor}}!</p>
              <p class="text-m font-semibold text-orange-700 mb-2">Contact Information</p>
              <div class="text-gray-600 mb-4">Landlord Phone {{ apt.doctor.phone_number }}</div>
              <button class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-700 transition duration-300 font-bold">
                <a href="{% url 'schedule_appointment' apt.id %}">Messages</a>
              </button>
              <button class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-700 transition duration-300 font-bold">
                <a href="{% url 'rate_doctor' apt.doctor.id %}">Rate Doctor</a>
              </button>
              <button class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-700 transition duration-300 font-bold">
                <a href="{% url 'join_the_call' apt.id %}">Join The Call</a>
              </button>

              
   
              
              {% endif %}

              {% if apt.status == 'pending' %}
              <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300 font-bold">
                <a href="{% url 'edit_appointment' apt.id %}">Edit Appointment</a>
                </button>
              <button class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-300 font-bold">
                <a href="{% url 'delete_appointment' apt.id %}">Delete Appointment</a>
                </button>
              {% endif %}
            </div>
            <div class="w-full md:w-1/3 mt-4 md:mt-0 md:ml-6">
              <img src="{{ apt.doctor.photo.url }}" class="w-full rounded" alt="Doctor's Image">
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div

{% endblock %}

appointments/templates/patients/edit_appointment.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="bg-gray-200 font-[sans-serif] text-[#333]">
  <div class="min-h-screen flex flex-col items-center justify-center py-6 px-4">
    <div class="max-w-3xl w-full border py-8 px-6 rounded border-gray-300 bg-white">
      <a href="javascript:void(0)"><img src="{% static '/images/logo.png' %}" alt="logo" class='w-40 mb-10' /></a>
 
      

    <form method="post" class="space-y-4">
      {% csrf_token %}
      <h1 class=" text-2xl font-extrabold text-gray-800">Edit Appointment</h1>

      <div class="space-y-4">
        <label for="id_appointment_date" class="block text-sm font-medium text-gray-700">{{form.appointment_date.label}}</label>
        <input type="datetime-local" name="appointment_date" value="{{ form.appointment_date.value|date:'c' }}">

      </div>
      
      <div class="space-y-4">
        <label for="id_address" class="block text-sm font-medium text-gray-700">{{form.additional_requests.label}}</label>
        <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
          {{ form.additional_requests}}
        </div>
      </div>

      <h3 class=" text-xl  font-bold text-red-800">Notice</h3>
      <h6 class=" text-xl  font-bold text-gray-600">The doctor will approve or decline your appointment request and notify you.</h6>


      <div class="flex items-center">
        <button type="submit" class="btn bg-blue-500 text-white items-cen hover:bg-blue-700 px-4 py-2 rounded">
          Edit Appointment
        </button>
      </div>
    </form>
  </div>
</div>
</section>

{% endblock %}

appointments/templates/patients/patient_appointments.html
{% extends 'doctors/dashboard.html' %}
{% load static %}

{% block dashboard_content %}

  <div class="lg:col-span-7 col-span-1 p-6 bg-gray-200 overflow-y-auto">
    <div class="container mx-auto p-6">
      <div class="bg-white shadow-md rounded-lg p-8">
        <h1 class="text-3xl font-bold text-gray-800 mb-4">Appointments</h1>
        <div class="grid gap-6">
          {% for apt in appointments %}

          <div class="bg-gray-100 shadow-sm rounded-lg p-6 flex flex-col md:flex-row items-center">
            <div class="w-full md:w-2/3">
              <div class="text-gray-600 mb-1">Appointment Date {{ apt.appointment_date }}</div>
              <div class="text-gray-600 mb-1">Requested on {{ apt.created_at  }}</div>
              <div class="text-gray-600 mb-1">Doctor {{ apt.doctor }}</div>
              <div class="text-gray-600 mb-4">Status: {{ apt.status }}</div>




              {% if apt.status == 'accepted' %}

              <p class="text-xl font-semibold text-green-700 mb-2">Your Request is Accepted!</p>
              <p class="text-m font-semibold text-orange-700 mb-2">Contact Information</p>
              <div class="text-gray-600 mb-4">Landlord Phone {{ apt.doctor.phone_number }}</div>
              <button class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-700 transition duration-300 font-bold">
                <a href="{% url 'schedule_appointment' apt.id %}">Start Chat</a>
              </button>
              <button class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-700 transition duration-300 font-bold">
                <a href="{% url 'schedule_appointment' apt.id %}">Start Video Call</a>
              </button>
              
   
              
              {% endif %}

              {% if apt.status == 'pending' %}
              <button class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-300 font-bold">
                <a href="{% url 'delete_appointment' apt.id %}">Delete Appointment</a>
                </button>
              {% endif %}
            </div>
            <div class="w-full md:w-1/3 mt-4 md:mt-0 md:ml-6">
              <img src="{{ apt.doctor.photo.url }}" class="w-full rounded" alt="Property Image">
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

appointments/templates/patients/schedule_appointment.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="bg-gray-200 font-[sans-serif] text-[#333]">
  <div class="min-h-screen flex flex-col items-center justify-center py-6 px-4">
    <div class="max-w-3xl w-full border py-8 px-6 rounded border-gray-300 bg-white">
      <a href="javascript:void(0)"><img src="{% static 'assets/images/logo.png' %}" alt="logo" class='w-40 mb-10' /></a>
 
      

    <form method="post" class="space-y-4">
      {% csrf_token %}
      <h1 class=" text-2xl font-extrabold text-gray-800">Schedule Appointment</h1>

      <div class="space-y-4">
        <label for="id_address" class="block text-sm font-medium text-gray-700">{{form.appointment_date.label}}</label>
        <input type="datetime-local" name="appointment_date" value="{{ form.appointment_date.value|date:'c' }}">
      </div>
      
      <div class="space-y-4">
        <label for="id_address" class="block text-sm font-medium text-gray-700">{{form.additional_requests.label}}</label>
        <div class="w-full text-sm px-3 py-2 rounded border border-gray-300 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50">
          {{ form.additional_requests}}
        </div>
      </div>

      <h3 class=" text-xl  font-bold text-red-800">Notice</h3>
      <h6 class=" text-xl  font-bold text-gray-600">The doctor will approve or decline your appointment request and notify you.</h6>


      <div class="flex items-center">
        <button type="submit" class="btn bg-blue-500 text-white items-cen hover:bg-blue-700 px-4 py-2 rounded">
          Schedule Appointment
        </button>
      </div>
    </form>
  </div>
</div>
</section>

{% endblock %}